services:
  pg:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
    - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432" # Useful to bind to localhost for inspecting with external tools like pgAdmin4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  data_collector:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /macd_param_analysis
    command: ["python3", "main.py"]
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/macd_param_analysis
      - ~/.ssh/:/root/.ssh/:ro  # Read-only mount of SSH keys if needed

  analysis_service:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /macd_param_analysis
    command: ["python3", "analysis.py"]
    depends_on:
      pg:
        condition: service_healthy
      data_collector:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./:/macd_param_analysis
      - ~/.ssh/:/root/.ssh/:ro  # Read-only mount of SSH keys if needed

volumes:
  pgdata:
  